apiVersion: v1
kind: Service
metadata:
  name: my-country-service
  namespace: jenkins
  labels:
    app: country-service
spec:
  type: NodePort
  selector:
    app: country-service
  ports:
  - name: http
    port: 8082
    targetPort: 8082
    nodePort: 30007
    protocol: TCP
